spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/board;
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create # 실행시점에 데이터를 지우고 다시실행
    properties:
      hibernate:
        #        show_sql: true # sql디버그(system.out)
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#    org.hibernate.type: trace
#    sql 디버그가 보임 (loger 를 통해)